server:
  port: 0

spring:
  application:
    name: user-service
  #db 설정
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

eureka:
  instance:
    hostname: localhost #gateway에 다는 게 아니라 service에 다는거임
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  #찾아보면 ip 값 받아오는 attribute 있을거임
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-Commerce.

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /application

feign:
  hystrix:
    enabled: true